configfile: 'config/mvp.yml'

# Global variables from the config file
bids_dir = config['bids_dir']
output_dir = config['output_dir']
script_dir = config['script_dir']
subjects = config['subjects']
sessions = config['sessions']

rule all:
    input:
        expand(
            "{output_dir}/micapipe_v0.2.0/sub-{subject}/ses-{session}/anat/sub-{subject}_ses-{session}_space-nativepro_T1w.nii.gz",
            subject=subjects,
            session=sessions,
            output_dir=output_dir
        )

rule proc_structural:
    input:
        bids_file="/data_/mica3/BIDS_CI/rawdata/sub-{subject}/ses-{session}/anat/sub-{subject}_ses-{session}_run-2_T1w.nii.gz"
    output:
        t1w_output="{output_dir}/micapipe_v0.2.0/sub-{subject}/ses-{session}/anat/sub-{subject}_ses-{session}_space-nativepro_T1w.nii.gz"
    params:
        tmpDir="{output_dir}/tmp",
        T1wStr=config["parameters"]["proc_structural"].get("T1wStr", "T1w.nii"),
        UNI=config["parameters"]["proc_structural"].get("UNI", "FALSE"),
        MF=config["parameters"]["proc_structural"].get("MF", 45),
        fs_licence="$FREESURFER_HOME/license.txt",
        micaq=config["parameters"]["proc_structural"].get("micaq", "FALSE"),
        qall=config["parameters"]["proc_structural"].get("qall", "FALSE"),
        nocleanup=config["parameters"]["proc_structural"].get("nocleanup", "FALSE")
        proc=config["parameters"]["proc_structural"].get("proc", "LOCAL")
    threads: config.get("threads", 4),
    log:
    shell:
        """
        log_file_str=$dir_logs/proc_structural_$(date +'%Y-%m-%d_%H.%M.%S')
        echo "Running structural processing for sub-{wildcards.subject}, ses-{wildcards.session}"
        
        COMMAND="{script_dir}/01_proc-structural.sh {bids_dir} sub-{wildcards.subject} {output_dir} {wildcards.session} \
                {params.nocleanup} {threads} {params.tmpDir} {params.T1wStr} {params.UNI} {params.MF}"
        if [[ {params.micaq} == "TRUE" ]]; then
            Info "MICA qsub - Structural processing: Volumetric"
            Warning "This option only works on the MICA workstations"
            export PROC="qsub-MICA"
            # Info "Setting a warper to run on mica.q"
            qsub -q mica.q -pe smp {params.threads} -l h_vmem=6G -N q${wildcards.subject}_volumetric -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
        # all.q - Structural processing: Volumetric
        elif [[ {params.qall} == "TRUE" ]]; then
            Info "all.q qsub - Structural processing: Volumetric"
            Warning "This option only works on the McGill BIC network"
            export PROC="qsub-all.q"
            # Info "Setting a warper to run on all.q"
            qsub -q all.q -pe all.pe {params.threads} -l h_vmem=6G -N q${wildcards.subject}_volumetric -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
        else
            export PROC="LOCAL"
            # LOCAL Structural processing: Volumetric
            $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
        fi
        """

